### ISSUE TITLE
Help text experience inconsistent

### ISSUE THREAD

**Issue by crcastle** [heroku/heroku-pipelines#46]
The behavior of `heroku pipelines --help` is inconsistent with the behavior of `heroku apps --help`, `heroku pg --help`, `heroku spaces --help`.  I believe the behavior of the latter ones is correct.

I think this will become increasingly important as new `pipelines`  sub-commands are added.  After Ike's demo showing `heroku pipelines:setup ...` I bumbled around trying to find help to see how the `setup` sub-command works.

It looks like `heroku pipelines --help` is interpreted as `heroku pipelines:list --help`:
```shell
👉  heroku pipelines --help
Usage: heroku pipelines:list

list pipelines you have access to

 --json              # output in json format

Example:
  $ heroku pipelines:list
  === My Pipelines
  example
  sushi
```

However, what I expect is something more similar to the output of `heroku apps --help`:
```shell
👉  heroku apps --help
Usage: heroku apps

list your apps

 -A, --all           # include apps in all organizations
 -o, --org ORG       # organization to use
 -p, --personal      # list apps in personal account when a default org is set
 -s, --space SPACE   # filter by space
 --json              # output in json format

Example:

 $ heroku apps
 === My Apps
 example
 example2

 === Collaborated Apps
 theirapp   other@owner.name

Commands for apps, type "heroku help apps:COMMAND" for more details:

 heroku apps                           # list your apps
 heroku apps:create [APP]              # create a new app
 heroku apps:destroy                   # permanently destroy an app
 heroku apps:errors                    # view app errors
 heroku apps:favorites                 # list favorited apps
 heroku apps:favorites:add             # favorites an app
 heroku apps:favorites:remove          # unfavorites an app
 heroku apps:fork                      # fork an existing app into a new one
 heroku apps:info                      # show detailed app information
 heroku apps:join                      # add yourself to an organization app
 heroku apps:leave                     # remove yourself from an organization app
 heroku apps:lock                      # prevent organization members from joining an app
 heroku apps:open [PATH]               # open the app in a web browser
 heroku apps:rename NEWNAME            # rename an app
 heroku apps:stacks                    # show the list of available stacks
 heroku apps:suspend                   # (sudo) suspend an app
 heroku apps:sync                      # (sudo) sync an app
 heroku apps:syncimplicits             # (sudo) syncs an apps implicit attachments
 heroku apps:transfer RECIPIENT        # transfer applications to another user, organization or team
 heroku apps:unlock                    # unlock an app so any organization member can join
 heroku apps:unsuspend                 # (sudo) unsuspend an app
```

If I have some time, I'll make a PR, but just wanted to get the issue documented first.

**Comment by raulb** [comment]
@crcastle Thanks for documenting this issue! I completely agree with you that including in the help only of the default command as the first output to later complete with additional commands is confusing. This is a default behavior that's coded by [heroku/cli](https://github.com/heroku/cli), not in `heroku-pipelines` exclusively. 

However, the output in `heroku pipelines --help` looks incomplete, not sure whether it's intentional or not. There was as recent issue in which some users experienced a shorten version of the command's help as it was only showing the help for the default command. This was fixed by @dickeyxxx [yesterday](https://github.com/heroku/cli/commit/ea745620f0106601940845316fb9beaaf50622af), so please let me/us know if it's otherwise.

For now, I'll close this issue since there isn't nothing to do here, but please feel free to post any update or further questions in regards to this command.

🥂
