### ISSUE TITLE
Provide a way to use `pipelines:setup` on a pipeline that's already configured

### ISSUE THREAD

**Issue by wadewegner** [heroku/heroku-pipelines#83]
Currently `pipelines:setup` create the apps for you. But there are cases where you already have these created and you want to add them to a newly created pipeline. And while you can do that today, you can't do it && run `pipelines:setup` to configure things like the assign git repo, enable review apps, etc.

Essentially, let me do the following (pseudo-code):

```
heroku apps:create mydev
heroku apps:create mystaging
heroku apps:create myprod

# ... configure those apps (vars, buildpacks, etc.) ...

heroku pipelines:create mypipe -a mydev-s development
heroku pipelines:add mypipe -a mystaging -s staging
heroku pipelines:add mypipe -a myprod -s production

# this is important because the app.json likely has required vars
heroku ci:config:set -p mypipe blah=blah

heroku pipelines:setup mypipe wadewegner/myrepo -y
```

Something like that.

**Comment by raulb** [comment]
@wadewegner That's an interesting use case I hadn't thought about. 

Since `pipelines:setup` currently operates with the assumption of users bootstrapping new pipelines, we'd need to rethink how to introduce a more granular action like connecting a pipeline to a repo, or some other configuration.

I wonder if introducing new commands for those purpose would make more sense. Something like:

```
heroku pipelines:connect mypipe wadewegner/myrepo
```

or 

```
heroku pipelines:reviewapps mypipe wadewegner/myrepo --enable
```

As a user, I'd imagined the command you'd like as part of `pipelines:update`, but that's currently doing something different, so this needs more thought. I'll see what I can do.

**Comment by wadewegner** [comment]
That sounds good. So long as it performs everything required -- i.e. enable review apps (with all the different flags/permutations), connect to a repo, choose which stage to copy for review apps, etc. I'd be down with this!

**Comment by raulb** [comment]
This will be completed in separate issues, part of this milestone: https://github.com/heroku/heroku-pipelines/milestone/1.
